name: A workflow for my Hello World file    # gives your workflow a name
on: push  # indicates that your workflow will execute anytime code is pushed to your repository, using the push event.

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"